stages:
  - build
  - deploy

variables:
  # Nom de l'image Docker (stockée dans le registre GitLab)
  IMAGE_TAG: $CI_REGISTRY_IMAGE:latest

# Étape 1 : Construire l'image Docker et la stocker chez GitLab
build_image:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - main

# Étape 2 : Se connecter au serveur et lancer le nouveau site
deploy_prod:
  stage: deploy
  image: alpine:latest
  before_script:
    # Installation du client SSH
    - apk add --no-cache openssh-client
    - eval $(ssh-agent -s)
    # On ajoute la clé privée stockée dans GitLab
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    # On accepte la clé du serveur automatiquement (pour éviter la question yes/no)
    - ssh-keyscan $SSH_IP >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - echo "Connexion au serveur..."
    - ssh $SSH_USER@$SSH_IP "
        docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY &&
        docker pull $IMAGE_TAG &&
        docker stop mon-portfolio || true &&
        docker rm mon-portfolio || true &&
        docker run -d --name mon-portfolio \
          --network mon_n8n_default \
          --restart always \
          $IMAGE_TAG"
  only:
    - main